// Generated by CoffeeScript 1.8.0
(function() {
  var app, express;

  express = require("express");

  app = express();

  app.use("/", express["static"]("client"));

  app.listen(8080);

}).call(this);
